### ISSUE TITLE
New address error with Byron address

### ISSUE THREAD

**Issue by crossle** [fivebinaries/go-cardano-serialization#7]
```
a, _ := address.NewAddress("DdzFFzCqrhsnBGYTEwPZry2YB27xmDtx7xQeozPPEeTjPJq9u1SwdYJNT4G5PxhRj1EudKW5m5XBy5xCVeKwLNQPfV4vxjqhQvBA7coP")
```
cbor: cannot unmarshal array into Go value of type address.ByronAddress (cannot decode CBOR array to struct without toarray option)

**Comment by HannesKimara** [comment]
@crossle Have a look at whether the recent merge fixes it for you.
